GET  http://localhost:3000/test-questions/deleteTest/test01
###
GET  http://localhost:3000/test-questions/test/test01

###
POST http://localhost:3000/test-questions/newTest
Content-Type: application/json

{
    "testId": "test03",
    "testName": "Test-03",
    "testDescription": "This is Test-03",
    "numberOfQuestions": 5,
    "testDuration": 15,
    "testStatus": "active",
    "testIsOpen": true
}

###
GET  http://localhost:3000/test-questions/questions

###
PATCH http://localhost:3000/test-questions/updateQuestion
Content-Type: application/json

{
    "questionId": "q1",
    "questionName": "Meaning of life"
}
 

###
POST http://localhost:3000/test-questions/newQuestion
Content-Type: application/json

{
        "questionId": "q11",
        "questionName": "Development Knowledge",
        "questionDescription": "What is correct MIME type for JSON ?",
        "answerOptions": [
            {
                "optionId": 1,
                "optionDescription": "json/mime",
                "isCorrect": false
            },
            {
                "optionId": 2,
                "optionDescription": "application/js",
                "isCorrect": false
            },
            {
                "optionId": 3,
                "optionDescription": "application/xml",
                "isCorrect": false
            },
            {
                "optionId": 4,
                "optionDescription": "none of these",
                "isCorrect": true
            }
        ],
        "correctAnswer": 4,
        "isPublished": true
    }


###
GET  http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{ 
    "username": "admin1",
    "fullName": "Admin User",
    "email": "admin1@mail.com",
    "password": "pass123",
    "isadmin": true,
    "role": "setter"
}




